# Generated by Django 5.0.3 on 2024-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_partner_delete_wife'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='driver_license_number',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
