# Generated by Django 5.0.3 on 2024-06-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0004_unite_remove_profile_station_remove_employe_station_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='unite',
            new_name='current_unite',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='validation',
        ),
        migrations.AddField(
            model_name='mission',
            name='total_validation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='unites',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
