# Generated by Django 5.0.3 on 2024-06-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0005_rename_unite_mission_current_unite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
