# Generated by Django 5.0.6 on 2024-06-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0007_logs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logs',
        ),
    ]
