# Generated by Django 5.0.6 on 2024-06-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0008_delete_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=90)),
                ('operation', models.CharField(max_length=40)),
                ('table', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
